"""Tests for cad_parser against a synthetic STEP fixture (generated by
tests/fixtures/generate_sample_part.py) containing a plate with a
through-hole, a countersunk hole, and a slot -- exercising plane, cylinder,
cone, slot-pairing, and standalone-circle-edge extraction.
"""

from pathlib import Path

import pytest

from cmm_gen.cad_parser import CADParseError, parse_step_file
from cmm_gen.models import FeatureType

FIXTURE = Path(__file__).parent / "fixtures" / "sample_part.step"


@pytest.fixture(scope="module")
def features():
    return parse_step_file(FIXTURE)


def test_parse_missing_file_raises() -> None:
    with pytest.raises(CADParseError):
        parse_step_file(Path("/nonexistent/part.step"))


def test_extracts_expected_feature_counts(features) -> None:
    counts: dict[FeatureType, int] = {}
    for f in features:
        counts[f.type] = counts.get(f.type, 0) + 1

    assert counts.get(FeatureType.PLANE, 0) == 8  # 6 box faces + 2 slot side walls
    assert counts.get(FeatureType.CYLINDER, 0) == 2  # through-hole + csk pilot hole
    assert counts.get(FeatureType.CONE, 0) == 1  # countersink
    assert counts.get(FeatureType.SLOT, 0) == 1  # paired half-cylinder ends
    assert counts.get(FeatureType.CIRCLE, 0) == 1  # csk rim edge, not a bore face


def test_through_hole_geometry(features) -> None:
    holes = [f for f in features if f.type == FeatureType.CYLINDER and f.diameter == 8.0]
    assert len(holes) == 1
    hole = holes[0]
    assert hole.depth == pytest.approx(15.0, abs=1e-2)
    assert abs(hole.nominal_vector.z) == pytest.approx(1.0, abs=1e-6)


def test_slot_geometry(features) -> None:
    slots = [f for f in features if f.type == FeatureType.SLOT]
    assert len(slots) == 1
    slot = slots[0]
    assert slot.diameter == pytest.approx(6.0, abs=1e-2)
    assert slot.nominal_location.x == pytest.approx(-15.0, abs=1e-2)
    assert slot.nominal_location.y == pytest.approx(-10.0, abs=1e-2)


def test_feature_ids_are_unique(features) -> None:
    ids = [f.id for f in features]
    assert len(ids) == len(set(ids))
